### ISSUE TITLE
Returns None when mode of iter has more than one

### ISSUE THREAD

**Issue by milesgranger** [BurntSushi/rust-stats#8]
Is this expected behavior?

```rust
let vec = vec![0, 0, 0, 1, 1, 1, 2];

assert_eq!(stats::mode(vec.into_iter()), None);
```

Seems to me it should return a `Vec<T>` rather than `T`

**Comment by BurntSushi** [comment]
I mean, the type signature says it either returns a single value or nothing, so it sounds like this is expected to me?

I don't have a problem adding another function that returns all possible modes, but I think the existing type signature, name and behavior is expected, yes.

**Comment by milesgranger** [comment]
Indeed it does as the signature promised..I'm sorry, I didn't mean _functionally_ expected behavior, but, I guess _logically_ expected...(for lack of better name).  

No hurry on adding that functionality; I really appreciate all your work in the Rust area. Makes it a bit more accessible for noobies like me. :)

**Comment by BurntSushi** [comment]
No problem! PRs are welcome for this. I don't know when I'll add it.

**Comment by milesgranger** [comment]
I'll take a stab at it.
